services:
  app:
    environment:
      DB_HOST: ${TEST_DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${TEST_DB_NAME}
      DB_USER: ${TEST_DB_USER}
      DB_PASSWORD: ${TEST_DB_PASSWORD}
    command: ["sh", "-c", "uv sync --frozen && uv run pytest -v"]
  db:
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
    - "5433:5432"