services:
  app:
    command: ["sh", "-c", "uv sync --frozen && uv run ./sensor_measurements.storage.py sensor_temperature battery_capacity"]
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"